// media_pipeline_tests.cpp — exercises Demuxer + VideoDecoder + AudioDecoder
// against a real (generated) sample file. Validates the spec 02 frame-identity
// invariant at the decode level: input frame count == decoded frame count,
// PTS preserved, no frames generated.
#include "media/Demuxer.hpp"
#include "media/VideoDecoder.hpp"
#include "media/AudioDecoder.hpp"

#include <cstdio>
#include <cstdlib>
#include <cstring>
#include <filesystem>

using namespace temporal_forge;

static int g_failures = 0;
#define CHECK(cond) do { \
    if (!(cond)) { std::fprintf(stderr, "FAIL %s:%d: %s\n", __FILE__, __LINE__, #cond); ++g_failures; } \
} while (0)

int main(int argc, char** argv) {
    // The sample file is generated by the test setup (ffmpeg testsrc2).
    std::string path;
    if (const char* env = std::getenv("TFORGE_SAMPLE")) path = env;
    else if (argc > 1) path = argv[1];
    else path = "sample.mp4";
    if (!std::filesystem::exists(path)) {
        std::fprintf(stderr, "media_pipeline_tests: SKIP (sample %s not found)\n", path.c_str());
        return 77; // skip
    }

    Demuxer demux;
    CHECK(demux.open(path));
    CHECK(demux.isOpen());

    const auto& info = demux.info();
    CHECK(info.videoIndex >= 0);
    CHECK(info.video != nullptr);
    CHECK(info.video->width == 640);
    CHECK(info.video->height == 360);
    // 5 seconds @ 30 fps = ~150 frames. Allow +/-2 for encoder rounding.
    CHECK(info.durationUs >= 4900000);

    VideoDecoder vdec;
    CHECK(vdec.open(demux.ctx(), info.videoIndex));
    CHECK(vdec.width() == 640);
    CHECK(vdec.height() == 360);

    // Decode the whole file; count frames and verify PTS monotonicity.
    int decodedFrames = 0;
    int64_t prevPts = -1;
    bool ptsMonotonic = true;
    bool colorMetadataPreserved = true;
    Packet pkt;
    while (demux.readPacket(pkt)) {
        if (pkt.streamIndex != info.videoIndex) continue;
        vdec.sendPacket(pkt.av);
        DecodedVideoFrame df;
        while (vdec.receiveFrame(df)) {
            ++decodedFrames;
            colorMetadataPreserved &= df.colorRange == AVCOL_RANGE_MPEG;
            colorMetadataPreserved &= df.colorSpace == AVCOL_SPC_BT709;
            if (prevPts >= 0 && df.ptsUs < prevPts) ptsMonotonic = false;
            prevPts = df.ptsUs;
        }
    }
    // Flush
    vdec.sendPacket(nullptr);
    DecodedVideoFrame df;
    while (vdec.receiveFrame(df)) {
        ++decodedFrames;
        colorMetadataPreserved &= df.colorRange == AVCOL_RANGE_MPEG;
        colorMetadataPreserved &= df.colorSpace == AVCOL_SPC_BT709;
    }

    CHECK(decodedFrames >= 145);       // ~150 expected
    CHECK(decodedFrames <= 155);
    CHECK(ptsMonotonic);
    CHECK(colorMetadataPreserved);

    std::printf("media_pipeline_tests: OK (decoded %d frames, last pts=%.3fs)\n",
                decodedFrames, prevPts / 1e6);
    return g_failures == 0 ? 0 : 1;
}
